DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0031.js", "first": "1", "last": "12" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "2" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "3" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "4" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "5" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "6.СТОРІНКА" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "8" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "9" },
	{ "fileName": "0xu0041.js", "first": "APPLE", "last": "APPLE" },
	{ "fileName": "0xu0043.js", "first": "CLINIC", "last": "CLINIC" },
	{ "fileName": "0xu0044.js", "first": "DENTAL", "last": "DENTAL" },
	{ "fileName": "0xu0045.js", "first": "E", "last": "E-MAIL/НОМЕРУ" },
	{ "fileName": "0xu0047.js", "first": "GOOGLE", "last": "GOOGLE/APPLE" },
	{ "fileName": "0xu004d.js", "first": "MAIL", "last": "MAP" },
	{ "fileName": "0xu0406.js", "first": "І", "last": "ІСТОРІЯМИ" },
	{ "fileName": "0xu0407.js", "first": "ЇХ", "last": "ЇХНЬОЇ" },
	{ "fileName": "0xu0410.js", "first": "А", "last": "АСПЕКТІВ" },
	{ "fileName": "0xu0411.js", "first": "БІЗНЕСУ", "last": "БУЛИ" },
	{ "fileName": "0xu0412.js", "first": "ВІДВІДУВАНОСТІ", "last": "ВХОДУ" },
	{ "fileName": "0xu0413.js", "first": "ГЛОСАРІЙ", "last": "ГОРІ" },
	{ "fileName": "0xu0414.js", "first": "ДІАГНОСТИКА", "last": "ДРУЗІВ" },
	{ "fileName": "0xu0415.js", "first": "ЕЛЕКТРОННОЇ", "last": "ЕФЕКТИВНУ" },
	{ "fileName": "0xu0417.js", "first": "З", "last": "ЗРУЧНОСТІ" },
	{ "fileName": "0xu0418.js", "first": "И", "last": "И" },
	{ "fileName": "0xu0419.js", "first": "ЙОГО", "last": "ЙОГО" },
	{ "fileName": "0xu041a.js", "first": "КІНЦІ", "last": "КРАЩОЇ" },
	{ "fileName": "0xu041b.js", "first": "ЛІКІВ", "last": "ЛОКАЦІЙНЕ" },
	{ "fileName": "0xu041c.js", "first": "МІЖ", "last": "МОЖЛИВІСТЬ" },
	{ "fileName": "0xu041d.js", "first": "НА", "last": "НОТАТОК" },
	{ "fileName": "0xu041e.js", "first": "ОБЛІК", "last": "ОСОБИСТОГО" },
	{ "fileName": "0xu041f.js", "first": "ПІДВИЩУВАТИ", "last": "ПРОЦЕСІВ" },
	{ "fileName": "0xu0420.js", "first": "РЕЄСТРАЦІЇ", "last": "РЯДКОМ" },
	{ "fileName": "0xu0421.js", "first": "САЙТУ", "last": "СТРУКТУРУВАТИ" },
	{ "fileName": "0xu0422.js", "first": "ТА", "last": "ТОЩО" },
	{ "fileName": "0xu0423.js", "first": "У", "last": "УПРАВЛІННЯ" },
	{ "fileName": "0xu0424.js", "first": "ФІЛІАЛІВ", "last": "ФУТЕР" },
	{ "fileName": "0xu0425.js", "first": "ХВОРОБИ", "last": "ХРОНОЛОГІЄЮ" },
	{ "fileName": "0xu0426.js", "first": "ЦІНИ", "last": "ЦЕНТРАЛЬНИЙ" },
	{ "fileName": "0xu0427.js", "first": "ЧАС", "last": "ЧИ" },
	{ "fileName": "0xu0428.js", "first": "ШВИДКИЙ", "last": "ШЛЯХОМ" },
	{ "fileName": "0xu0429.js", "first": "ЩО", "last": "ЩОДО" },
	{ "fileName": "0xu042f.js", "first": "ЯК", "last": "ЯКА" }
];